apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: boards
spec:
  hosts:
  - boards
  http:
  - fault:
      abort:
        httpStatus: 500
        percent: 50
    route:
    - destination:
        host: boards