# These are a set of destination rules that can be used
# as a simple base for more advanced demos to build upon
#
# you use destination rules to configure what happens to traffic (the destination itself is set in a virtual service)
# Destination rules are applied after virtual service routing rules are evaluated
# read more here: https://istio.io/docs/reference/config/networking/destination-rule/
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: app-ui
spec:
  host: app-ui
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: boards
spec:
  host: boards
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: boards-mongodb
spec:
  host: boards-mongodb
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: context-scraper
spec:
  host: context-scraper
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: userprofile
spec:
  host: userprofile