#
# You will need to replace the rootUrl below with your proper path
#
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: client-app
  labels:
    app: sso
    app.realm: microservices-demo
  namespace: sso-shared
spec:
  realmSelector:
    matchLabels:
      app.realm: microservices-demo
  client:
    description: "Microservices demo application UI clients"
    clientId: client-app
    # secret: client-secret
    # clientAuthenticatorType: client-secret
    publicClient: true
    redirectUris:
    - "https://*"
    - "http://*"
    - "/*"
    rootUrl: "http://istio-ingressgateway-istio-system.apps.leonardo.nub3s.io/"
    directAccessGrantsEnabled: true
